MyPage/Models/Hotels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels
    {
        public int PKID { get; set; }
        public string HotelName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string FKHotelGroupCode { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string HotelGeneralManagerName { get; set; }
        public string HotelGeneralManagerEmail { get; set; }
        public string HotelGeneralManagerPhone { get; set; }
        public string HotelContactPerson1Title { get; set; }
        public string HotelContactPerson1Name { get; set; }
        public string HotelContactPerson1Phone { get; set; }
        public string HotelContactPerson1Email { get; set; }
        public string HotelContactPerson2Title { get; set; }
        public string HotelContactPerson2Name { get; set; }
        public string HotelContactPerson2Phone { get; set; }
        public string HotelContactPerson2Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<decimal> HotelBonus { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; }
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public string HotelPic { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}

MyPage/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using MyPage.Models;

namespace MyPage.Controllers
{
    public class HotelsController : BaseController

    {

        // GET: Hotels
        [Authorize]
        public ActionResult Index()
        {

            ViewBag.HotelRoomCountList = getHotelRoomCounts();
                

            return View(db.Hotels.ToList());
        }
       
        


        // GET: Hotels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotels hotels = db.Hotels.Find(id);
            if (hotels == null)
            {
                return HttpNotFound();
            }
            return View(hotels);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            ViewBag.CompanyNameList = GetCompanyList();
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PKID,HotelName,Active,Email,WebAddress,Phone,HotelGeneralManagerName,HotelGeneralManagerEmail,HotelGeneralManagerPhone,HotelContactPerson1Title,HotelContactPerson1Name,HotelContactPerson1Phone,HotelContactPerson1Email,Address1,City,Country,ZipCode,HotelBonus,RecorderDate,RecorderUser,ModifierDate,ModifierUser,SortOrder")] Hotels hotels)
        {
            if (ModelState.IsValid)
            {
                db.Hotels.Add(hotels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hotels);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotels hotels = db.Hotels.Find(id);
            if (hotels == null)
            {
                return HttpNotFound();
            }
            return View(hotels);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PKID,HotelName,Active,FKHotelGroupCode,Email,WebAddress,Phone,MobilePhone,HotelGeneralManagerName,HotelGeneralManagerEmail,HotelGeneralManagerPhone,HotelContactPerson1Title,HotelContactPerson1Name,HotelContactPerson1Phone,HotelContactPerson1Email,HotelContactPerson2Title,HotelContactPerson2Name,HotelContactPerson2Phone,HotelContactPerson2Email,Address1,Address2,City,State,Country,ZipCode,HotelBonus,RecorderDate,RecorderUser,ModifierDate,ModifierUser,HotelPic,SortOrder")] Hotels hotels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotels);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotels hotels = db.Hotels.Find(id);
            if (hotels == null)
            {
                return HttpNotFound();
            }
            return View(hotels);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotels hotels = db.Hotels.Find(id);
            db.Hotels.Remove(hotels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPage/Views/Hotels/Create.cshtml
@model MyPage.Models.Hotels

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var CompanyList = ViewBag.CompanyNameList as Dictionary<int, string>;
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Hotels</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">

    @using (Html.BeginForm("Create", "Hotels", FormMethod.Post))
    {
        <div class="form-group">
            <label for="HotelName">Select Company</label>
            <select name="HotelName" class="form-control">
                @if ( CompanyList != null)
                {
                    foreach (var company in CompanyList)
                    {
                        <option value="@company.Value">@company.Value</option>
                    }
                }
                else
                {
                    <option>No Company found.</option>
                }
            </select>
        </div>        
    }   
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        fk hotel isimleri buraya gelecek
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.WebAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.HotelGeneralManagerName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelGeneralManagerName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelGeneralManagerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelGeneralManagerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelGeneralManagerEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelGeneralManagerEmail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelGeneralManagerPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelGeneralManagerPhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelGeneralManagerPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelContactPerson1Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelContactPerson1Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelContactPerson1Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelContactPerson1Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelContactPerson1Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelContactPerson1Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelContactPerson1Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelContactPerson1Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelContactPerson1Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelContactPerson1Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelContactPerson1Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelContactPerson1Email, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HotelBonus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HotelBonus, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HotelBonus, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RecorderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RecorderDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RecorderDate, "", new { @class = "text-danger" })
        </div>
    </div>

    @*RECORDER USER BURDAYDI *@

    <div class="form-group">
        @Html.LabelFor(model => model.ModifierDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ModifierDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ModifierDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ModifierUser, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ModifierUser, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ModifierUser, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.SortOrder, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SortOrder, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SortOrder, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyPage/Views/Hotels/Delete.cshtml
@model MyPage.Models.Hotels

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotels</h4>  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HotelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>

            hotel adılarının başlığıda burda
        </dt>

        <dd>
            otel listesi burda görünecek
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Email)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelBonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelBonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecorderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecorderDate)
        </dd>

        @*RECORDER USER BURDAYDI *@
        <dd>
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifierUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SortOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortOrder)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyPage/Views/Hotels/Details.cshtml
@model MyPage.Models.Hotels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Hotels</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HotelName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelGeneralManagerPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelGeneralManagerPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Name)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.HotelContactPerson1Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelContactPerson1Email)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HotelBonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HotelBonus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecorderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecorderDate)
        </dd>
        @*RECORDER USER BURDAYDI *@
        <dt>
            @Html.DisplayNameFor(model => model.ModifierDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifierUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierUser)
        </dd>



        <dt>
            @Html.DisplayNameFor(model => model.SortOrder)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SortOrder)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PKID }) |
    @Html.ActionLink("Back to List", "Index")
</p>