MyPage/Models/Bookers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookers
    {
        public int PKID { get; set; }
        public string FKCompanyID { get; set; }
        public string HotelGroupCode { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> RecorderDate { get; set; } = DateTime.Now;
        public string RecorderUser { get; set; }
        public Nullable<System.DateTime> ModifierDate { get; set; }
        public string ModifierUser { get; set; }
        public string Role { get; set; }
        public string AgencyName { get; set; }
        public string AgencyEmail { get; set; }
        public string AgencyWebAddress { get; set; }
        public string AgencyAddress { get; set; }
        public string AgencyPhone { get; set; }
        public string AgencyLicence { get; set; }
        public string AgencyOwner { get; set; }
        public string AgencyZipCode { get; set; }
        public string AgencyCity { get; set; }
        public string AgencyCountry { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> ConfirmKVVK { get; set; }
    }
}

MyPage/Controllers/BookersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPage.Models;

namespace MyPage.Controllers
{
    public class BookersController : BaseController
    {

        public ActionResult hotelnames()
        {
           
            return View();
        }

        [Authorize]
        // GET: Bookers
        public ActionResult Index()
        {
            ViewBag.GetCompanyListToBookers = GetCompanyListToBookers();
            var categories = db.Bookers.Take(20).ToList();
            ViewBag.Categories = new SelectList(categories, "Country");


            return View(db.Bookers.ToList());
        }

        // GET: Bookers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookers bookers = db.Bookers.Find(id);
            if (bookers == null)
            {
                return HttpNotFound();
            }
            return View(bookers);
        }

        // GET: Bookers/Create
        public ActionResult Create()
        {
            ViewBag.CompanyNameList = GetCompanyList();
            
            return View();
        }

        // POST: Bookers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PKID,FKCompanyID,HotelGroupCode,Active,Email,Pass,FirstName,LastName,Phone,MobilePhone,Address1,Address2,City,State,Country,RecorderDate,RecorderUser,ModifierDate,ModifierUser,Role,AgencyName,AgencyEmail,AgencyWebAddress,AgencyAddress,AgencyPhone,AgencyLicence,AgencyOwner,AgencyZipCode,AgencyCity,AgencyCountry,Gender,ConfirmKVVK")] Bookers bookers)
        {
            if (ModelState.IsValid)
            {
                db.Bookers.Add(bookers);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bookers);
        }

        // GET: Bookers/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.CompanyNameList = GetCompanyList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookers bookers = db.Bookers.Find(id);
            if (bookers == null)
            {
                return HttpNotFound();
            }
            return View(bookers);
        }

        // POST: Bookers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PKID,FKCompanyID,HotelGroupCode,Active,Email,Pass,FirstName,LastName,Phone,MobilePhone,Address1,Address2,City,State,Country,RecorderDate,RecorderUser,ModifierDate,ModifierUser,Role,AgencyName,AgencyEmail,AgencyWebAddress,AgencyAddress,AgencyPhone,AgencyLicence,AgencyOwner,AgencyZipCode,AgencyCity,AgencyCountry,Gender,ConfirmKVVK")] Bookers bookers)
        {
            ViewBag.CompanyNameList = GetCompanyList();
            if (ModelState.IsValid)
            {
                db.Entry(bookers).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookers);
        }

        // GET: Bookers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bookers bookers = db.Bookers.Find(id);
            if (bookers == null)
            {
                return HttpNotFound();
            }
            return View(bookers);
        }

        // POST: Bookers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bookers bookers = db.Bookers.Find(id);
            db.Bookers.Remove(bookers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyPage/Views/Bookers/Create.cshtml
@model MyPage.Models.Bookers

@{
    ViewBag.Title = "Create";

    Layout = "~/Views/Shared/_Layout.cshtml";
    var liste = ViewBag.liste as List<string>;
    var CompanyList = ViewBag.CompanyNameList as Dictionary<int, string>;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Bookers</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     

<div class="form-group">

    @using (Html.BeginForm("Create", "Bookers", FormMethod.Post))
    {
        <div class="form-group">
            <label for="FKCompanyID">Select Company</label>
            <select name="FKCompanyID" class="form-control">
                @if (CompanyList != null)
                {
                    foreach (var company in CompanyList)
                    {
                        <option value="@company.Key">@company.Value</option>
                    }
                }
                else
                {
                    <option>No Company found.</option>
                }
            </select>
        </div>
    }
</div>





    <div class="form-group">
        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Active)
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pass, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pass, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>   

    <div class="form-group">
        @Html.LabelFor(model => model.RecorderDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @DateTime.Now
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ModifierDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.EditorFor(model => model.ModifierDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ModifierDate, "", new { @class = "text-danger" })
        </div>
    </div>
    

    <div class="form-group">
        @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyEmail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyEmail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyEmail, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.AgencyAddress, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyAddress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyPhone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyPhone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyPhone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyLicence, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyLicence, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyLicence, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyOwner, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyOwner, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyOwner, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyZipCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyZipCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyCity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyCity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyCity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AgencyCountry, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AgencyCountry, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AgencyCountry, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        <fieldset>
            <h6>Select your gender</h6>
            @Html.RadioButtonFor(model => model.Gender, "Male", new { id = "radio-male" })
            <label for="radio-male">Male</label>
            @Html.RadioButtonFor(model => model.Gender, "Female", new { id = "radio-female" })
            <label for="radio-female">Female</label>
            @Html.RadioButtonFor(model => model.Gender, "Prefer not to specify", new { id = "radio-prefer-not-to-specify" })
            <label for="radio-prefer-not-to-specify">Prefer not to specify</label>


        </fieldset>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmKVVK, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">


                @if (Model != null)
                {
                    @Html.CheckBox("ConfirmKVVK", Model.ConfirmKVVK ?? false)
                }
                else
                {
                    @Html.CheckBox("ConfirmKVVK", false)
                }

                @Html.ValidationMessageFor(model => model.ConfirmKVVK, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyPage/Views/Bookers/Delete.cshtml
@model MyPage.Models.Bookers

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bookers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FKCompanyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FKCompanyID)
        </dd>
               

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecorderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecorderDate)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.ModifierDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifierUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyWebAddress)
        </dt>

       

        <dd>
            @Html.DisplayFor(model => model.AgencyAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyLicence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyLicence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyOwner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyOwner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmKVVK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmKVVK)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyPage/Views/Bookers/Details.cshtml
@model MyPage.Models.Bookers

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Bookers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FKCompanyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FKCompanyID)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

       

        <dt>
            @Html.DisplayNameFor(model => model.RecorderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecorderDate)
        </dd>      

        <dt>
            @Html.DisplayNameFor(model => model.ModifierDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifierUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifierUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyEmail)
        </dd>        

        <dt>
            @Html.DisplayNameFor(model => model.AgencyAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyLicence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyLicence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyOwner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyOwner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyCity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyCity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgencyCountry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgencyCountry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmKVVK)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmKVVK)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PKID }) |
    @Html.ActionLink("Back to List", "Index")
</p>